apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_DB
          value: jenkins
        - name: INFLUXDB_USER
          value: admin
        - name: INFLUXDB_USER_PASSWORD
          value: admin
        image: influxdb:1.4
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb
      restartPolicy: Always
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb
status: {}
