apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nifi
  name: nifi
spec:
  ports:
  - name: "6004"
    port: 6004
    targetPort: 6004
  selector:
    io.kompose.service: nifi
status:
  loadBalancer: {}
